### ISSUE TITLE
Add authentication options for client

### ISSUE THREAD

**Issue by j18e** [tdabasinskas/go-backstage#36]
Some recent versions of Backstage introduce authentication via bearer tokens. The `NewClient` function allows for providing one's own HTTP client and notes "To use API methods which require authentication, provide a http.Client that will perform the authentication.", however I don't see that it's possible to add an Authorization header to every request made by the client. That would have to be done inside the package.

My suggestion is to add a token field to NewClient where one could optionally provide the bearer token and have it added to all the requests made to Backstage. I'll be trying this out in my fork https://github.com/j18e/go-backstage but there could be other ways to achieve it. What do you think @tdabasinskas ?

**Comment by tdabasinskas** [comment]
Hi @j18e ,

Have you checked #11?

**Comment by j18e** [comment]
You're absolutely right, that does the trick. But maybe I'll submit a PR that adds a comment telling how one can authenticate.

Thanks for the quick response!
